# Dart analyzer configuration for G20
include: package:flutter_lints/flutter.yaml

analyzer:
  # Only fail on errors, not warnings or info
  errors:
    # Treat these as info (don't fail CI)
    unused_import: info
    unused_element: info
    unused_field: info
    unused_local_variable: info
    deprecated_member_use: info
    invalid_use_of_protected_member: info
    invalid_use_of_visible_for_testing_member: info
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    unnecessary_import: info
    unnecessary_null_comparison: info
    unnecessary_non_null_assertion: info
    dead_null_aware_expression: info
    dangling_library_doc_comments: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_string_interpolations: ignore
    avoid_print: ignore
    depend_on_referenced_packages: info
    use_build_context_synchronously: info
    body_might_complete_normally_catch_error: warning
    prefer_final_fields: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

linter:
  rules:
    # Disable overly strict rules
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    prefer_final_fields: false
    unnecessary_brace_in_string_interps: false
    dangling_library_doc_comments: false
